// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__traceChgSub0(Vtop___024root* vlSelf, VerilatedVcd* tracep);

void Vtop___024root__traceChgTop0(void* voidSelf, VerilatedVcd* tracep) {
    Vtop___024root* const __restrict vlSelf = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    {
        Vtop___024root__traceChgSub0((&vlSymsp->TOP), tracep);
    }
}

void Vtop___024root__traceChgSub0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode + 1);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[0U])) {
            tracep->chgIData(oldp+0,(vlSelf->top__DOT__de__DOT__r0__DOT__i),32);
            tracep->chgQData(oldp+1,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__pair_list[0]),37);
            tracep->chgIData(oldp+3,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__key_list[0]),32);
            tracep->chgCData(oldp+4,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__data_list[0]),5);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[1U])) {
            tracep->chgIData(oldp+5,(vlSelf->top__DOT__dnpc),32);
            tracep->chgQData(oldp+6,(vlSelf->top__DOT__de__DOT__mraddr),64);
            tracep->chgQData(oldp+8,(vlSelf->top__DOT__de__DOT__mrdata),64);
            tracep->chgQData(oldp+10,(vlSymsp->TOP__top__DOT__de__DOT__m10.out),64);
            tracep->chgQData(oldp+12,(vlSymsp->TOP__top__DOT__de__DOT__m9.out),64);
            tracep->chgCData(oldp+14,(vlSelf->top__DOT__de__DOT__mwmask),8);
            tracep->chgIData(oldp+15,((IData)(vlSelf->top__DOT__de__DOT__rdata)),32);
            tracep->chgCData(oldp+16,(vlSelf->top__DOT__de__DOT__call_return),2);
            tracep->chgIData(oldp+17,(vlSelf->top__DOT__de__DOT__call_return),32);
            tracep->chgCData(oldp+18,(vlSelf->top__DOT__de__DOT__Type),3);
            tracep->chgIData(oldp+19,(vlSelf->top__DOT__de__DOT__Type),32);
            tracep->chgCData(oldp+20,(vlSelf->top__DOT__de__DOT__raddr),5);
            tracep->chgQData(oldp+21,(vlSelf->top__DOT__de__DOT__src1),64);
            tracep->chgQData(oldp+23,(vlSelf->top__DOT__de__DOT__src2),64);
            tracep->chgQData(oldp+25,(vlSelf->top__DOT__de__DOT__rdata),64);
            tracep->chgQData(oldp+27,(vlSymsp->TOP__top__DOT__de__DOT__m1.out),64);
            tracep->chgQData(oldp+29,(vlSymsp->TOP__top__DOT__de__DOT__m7.out),64);
            tracep->chgCData(oldp+31,(vlSelf->top__DOT__de__DOT__waddr),5);
            tracep->chgQData(oldp+32,(vlSelf->top__DOT__de__DOT__wdata),64);
            tracep->chgQData(oldp+34,(vlSelf->top__DOT__de__DOT__addresult),64);
            tracep->chgQData(oldp+36,(vlSymsp->TOP__top__DOT__de__DOT__m4.out),64);
            tracep->chgQData(oldp+38,(vlSymsp->TOP__top__DOT__de__DOT__m5.out),64);
            tracep->chgQData(oldp+40,(vlSelf->top__DOT__de__DOT__compare),64);
            tracep->chgQData(oldp+42,(vlSelf->top__DOT__de__DOT__logr),64);
            tracep->chgQData(oldp+44,(vlSelf->top__DOT__de__DOT__arir),64);
            tracep->chgQData(oldp+46,(vlSelf->top__DOT__de__DOT__logl),64);
            tracep->chgQData(oldp+48,(vlSelf->top__DOT__de__DOT__aril),64);
            tracep->chgQData(oldp+50,(vlSelf->top__DOT__de__DOT__yu),64);
            tracep->chgQData(oldp+52,(vlSelf->top__DOT__de__DOT__huo),64);
            tracep->chgQData(oldp+54,(vlSelf->top__DOT__de__DOT__yihuo),64);
            tracep->chgQData(oldp+56,(vlSelf->top__DOT__de__DOT__cheng),64);
            tracep->chgQData(oldp+58,(vlSelf->top__DOT__de__DOT__chu),64);
            tracep->chgQData(oldp+60,(vlSelf->top__DOT__de__DOT__scheng),64);
            tracep->chgQData(oldp+62,(vlSelf->top__DOT__de__DOT__schu),64);
            tracep->chgQData(oldp+64,(vlSelf->top__DOT__de__DOT__syu),64);
            tracep->chgIData(oldp+66,(vlSelf->top__DOT__de__DOT__addi),32);
            tracep->chgIData(oldp+67,(vlSelf->top__DOT__de__DOT__andi),32);
            tracep->chgIData(oldp+68,(vlSelf->top__DOT__de__DOT__xori),32);
            tracep->chgIData(oldp+69,(vlSelf->top__DOT__de__DOT__ori),32);
            tracep->chgIData(oldp+70,(vlSelf->top__DOT__de__DOT__sllw),32);
            tracep->chgIData(oldp+71,(vlSelf->top__DOT__de__DOT__sll),32);
            tracep->chgIData(oldp+72,(vlSelf->top__DOT__de__DOT__srlw),32);
            tracep->chgIData(oldp+73,(vlSelf->top__DOT__de__DOT__sraw),32);
            tracep->chgIData(oldp+74,(vlSelf->top__DOT__de__DOT__srawd),32);
            tracep->chgIData(oldp+75,(vlSelf->top__DOT__de__DOT__addiw),32);
            tracep->chgIData(oldp+76,(vlSelf->top__DOT__de__DOT__slliw),32);
            tracep->chgIData(oldp+77,(vlSelf->top__DOT__de__DOT__srliw),32);
            tracep->chgIData(oldp+78,(vlSelf->top__DOT__de__DOT__sraiw),32);
            tracep->chgQData(oldp+79,(vlSelf->top__DOT__de__DOT__addauipc),64);
            tracep->chgQData(oldp+81,(vlSelf->top__DOT__de__DOT__luimid),64);
            tracep->chgIData(oldp+83,(vlSelf->top__DOT__de__DOT__jalr),32);
            tracep->chgIData(oldp+84,(vlSelf->top__DOT__de__DOT__sd),32);
            tracep->chgIData(oldp+85,(vlSelf->top__DOT__de__DOT__sh),32);
            tracep->chgIData(oldp+86,(vlSelf->top__DOT__de__DOT__sw),32);
            tracep->chgIData(oldp+87,(vlSelf->top__DOT__de__DOT__sb),32);
            tracep->chgIData(oldp+88,(vlSelf->top__DOT__de__DOT__lw),32);
            tracep->chgIData(oldp+89,(vlSelf->top__DOT__de__DOT__lh),32);
            tracep->chgIData(oldp+90,(vlSelf->top__DOT__de__DOT__lb),32);
            tracep->chgIData(oldp+91,(vlSelf->top__DOT__de__DOT__lbu),32);
            tracep->chgIData(oldp+92,(vlSelf->top__DOT__de__DOT__lwu),32);
            tracep->chgIData(oldp+93,(vlSelf->top__DOT__de__DOT__lhu),32);
            tracep->chgIData(oldp+94,(vlSelf->top__DOT__de__DOT__ld),32);
            tracep->chgIData(oldp+95,(vlSelf->top__DOT__de__DOT__addw),32);
            tracep->chgIData(oldp+96,(vlSelf->top__DOT__de__DOT__subw),32);
            tracep->chgIData(oldp+97,(vlSelf->top__DOT__de__DOT__mulw),32);
            tracep->chgIData(oldp+98,(vlSelf->top__DOT__de__DOT__divw),32);
            tracep->chgIData(oldp+99,(vlSelf->top__DOT__de__DOT__divuw),32);
            tracep->chgIData(oldp+100,(vlSelf->top__DOT__de__DOT__div),32);
            tracep->chgIData(oldp+101,(vlSelf->top__DOT__de__DOT__remw),32);
            tracep->chgIData(oldp+102,(vlSelf->top__DOT__de__DOT__Add),32);
            tracep->chgIData(oldp+103,(vlSelf->top__DOT__de__DOT__Mul),32);
            tracep->chgIData(oldp+104,(vlSelf->top__DOT__de__DOT__And),32);
            tracep->chgIData(oldp+105,(vlSelf->top__DOT__de__DOT__Xor),32);
            tracep->chgIData(oldp+106,(vlSelf->top__DOT__de__DOT__Or),32);
            tracep->chgIData(oldp+107,(vlSelf->top__DOT__de__DOT__sltu),32);
            tracep->chgIData(oldp+108,(vlSelf->top__DOT__de__DOT__slt),32);
            tracep->chgIData(oldp+109,(vlSelf->top__DOT__de__DOT__sub),32);
            tracep->chgIData(oldp+110,(vlSelf->top__DOT__de__DOT__sltiu),32);
            tracep->chgIData(oldp+111,(vlSelf->top__DOT__de__DOT__srai),32);
            tracep->chgIData(oldp+112,(vlSelf->top__DOT__de__DOT__slli),32);
            tracep->chgIData(oldp+113,(vlSelf->top__DOT__de__DOT__srli),32);
            tracep->chgIData(oldp+114,(vlSelf->top__DOT__de__DOT__beq),32);
            tracep->chgIData(oldp+115,(vlSelf->top__DOT__de__DOT__bne),32);
            tracep->chgIData(oldp+116,(vlSelf->top__DOT__de__DOT__bge),32);
            tracep->chgIData(oldp+117,(vlSelf->top__DOT__de__DOT__bgeu),32);
            tracep->chgIData(oldp+118,(vlSelf->top__DOT__de__DOT__bltu),32);
            tracep->chgIData(oldp+119,(vlSelf->top__DOT__de__DOT__blt),32);
            tracep->chgWData(oldp+120,(vlSelf->top__DOT__de__DOT____Vcellinp__m0____pinNumber4),1820);
            tracep->chgCData(oldp+177,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__lut_out),3);
            tracep->chgBit(oldp+178,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+179,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+180,(vlSelf->top__DOT__de__DOT____Vcellinp__m2____pinNumber4),1554);
            tracep->chgCData(oldp+229,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__lut_out),5);
            tracep->chgBit(oldp+230,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+231,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+232,(vlSelf->top__DOT__de__DOT____Vcellinp__m3____pinNumber4),4032);
            tracep->chgQData(oldp+358,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+360,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+361,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__i),32);
            tracep->chgCData(oldp+362,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__lut_out),5);
            tracep->chgBit(oldp+363,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+364,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+365,(vlSelf->top__DOT__de__DOT____Vcellinp__m6____pinNumber4),512);
            tracep->chgQData(oldp+381,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[0]),64);
            tracep->chgQData(oldp+383,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[1]),64);
            tracep->chgQData(oldp+385,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[2]),64);
            tracep->chgQData(oldp+387,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[3]),64);
            tracep->chgQData(oldp+389,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[4]),64);
            tracep->chgQData(oldp+391,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[5]),64);
            tracep->chgQData(oldp+393,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[6]),64);
            tracep->chgQData(oldp+395,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[7]),64);
            tracep->chgIData(oldp+397,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+398,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+399,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+400,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[3]),32);
            tracep->chgIData(oldp+401,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[4]),32);
            tracep->chgIData(oldp+402,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[5]),32);
            tracep->chgIData(oldp+403,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[6]),32);
            tracep->chgIData(oldp+404,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[7]),32);
            tracep->chgIData(oldp+405,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[0]),32);
            tracep->chgIData(oldp+406,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[1]),32);
            tracep->chgIData(oldp+407,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[2]),32);
            tracep->chgIData(oldp+408,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[3]),32);
            tracep->chgIData(oldp+409,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[4]),32);
            tracep->chgIData(oldp+410,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[5]),32);
            tracep->chgIData(oldp+411,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[6]),32);
            tracep->chgIData(oldp+412,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[7]),32);
            tracep->chgIData(oldp+413,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__lut_out),32);
            tracep->chgBit(oldp+414,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+415,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+416,(vlSelf->top__DOT__de__DOT____Vcellinp__m12____pinNumber4),160);
            tracep->chgQData(oldp+421,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[0]),40);
            tracep->chgQData(oldp+423,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[1]),40);
            tracep->chgQData(oldp+425,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[2]),40);
            tracep->chgQData(oldp+427,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[3]),40);
            tracep->chgIData(oldp+429,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+430,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+431,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+432,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[3]),32);
            tracep->chgCData(oldp+433,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[0]),8);
            tracep->chgCData(oldp+434,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[1]),8);
            tracep->chgCData(oldp+435,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[2]),8);
            tracep->chgCData(oldp+436,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[3]),8);
            tracep->chgCData(oldp+437,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__lut_out),8);
            tracep->chgBit(oldp+438,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+439,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+440,(vlSelf->top__DOT__de__DOT____Vcellinp__m14____pinNumber4),672);
            tracep->chgWData(oldp+461,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+464,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+467,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+470,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[3]),96);
            tracep->chgWData(oldp+473,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[4]),96);
            tracep->chgWData(oldp+476,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[5]),96);
            tracep->chgWData(oldp+479,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[6]),96);
            tracep->chgIData(oldp+482,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+483,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+484,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+485,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[3]),32);
            tracep->chgIData(oldp+486,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[4]),32);
            tracep->chgIData(oldp+487,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[5]),32);
            tracep->chgIData(oldp+488,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[6]),32);
            tracep->chgQData(oldp+489,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+491,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+493,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+495,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+497,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+499,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[5]),64);
            tracep->chgQData(oldp+501,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[6]),64);
            tracep->chgQData(oldp+503,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+505,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+506,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+507,(vlSelf->top__DOT__de__DOT____Vcellinp__m9____pinNumber4),384);
            tracep->chgWData(oldp+519,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+522,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+525,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+528,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[3]),96);
            tracep->chgIData(oldp+531,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+532,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+533,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+534,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[3]),32);
            tracep->chgQData(oldp+535,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+537,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+539,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+541,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+543,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+545,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+546,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+547,(vlSelf->top__DOT__de__DOT____Vcellinp__m10____pinNumber4),384);
            tracep->chgWData(oldp+559,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+562,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+565,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+568,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[3]),96);
            tracep->chgIData(oldp+571,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+572,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+573,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+574,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[3]),32);
            tracep->chgQData(oldp+575,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+577,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+579,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+581,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+583,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+585,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+586,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+587,(vlSelf->top__DOT__de__DOT____Vcellinp__m4____pinNumber4),4608);
            tracep->chgQData(oldp+731,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+733,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+734,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+735,(vlSelf->top__DOT__de__DOT____Vcellinp__m5____pinNumber4),4608);
            tracep->chgQData(oldp+879,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+881,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+882,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+883,(vlSelf->top__DOT__de__DOT____Vcellinp__m1____pinNumber4),402);
            tracep->chgWData(oldp+896,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[0]),67);
            tracep->chgWData(oldp+899,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[1]),67);
            tracep->chgWData(oldp+902,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[2]),67);
            tracep->chgWData(oldp+905,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[3]),67);
            tracep->chgWData(oldp+908,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[4]),67);
            tracep->chgWData(oldp+911,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[5]),67);
            tracep->chgCData(oldp+914,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[0]),3);
            tracep->chgCData(oldp+915,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[1]),3);
            tracep->chgCData(oldp+916,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[2]),3);
            tracep->chgCData(oldp+917,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[3]),3);
            tracep->chgCData(oldp+918,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[4]),3);
            tracep->chgCData(oldp+919,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[5]),3);
            tracep->chgQData(oldp+920,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+922,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+924,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+926,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+928,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+930,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[5]),64);
            tracep->chgQData(oldp+932,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+934,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+935,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+936,(vlSelf->top__DOT__de__DOT____Vcellinp__m7____pinNumber4),402);
            tracep->chgWData(oldp+949,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[0]),67);
            tracep->chgWData(oldp+952,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[1]),67);
            tracep->chgWData(oldp+955,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[2]),67);
            tracep->chgWData(oldp+958,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[3]),67);
            tracep->chgWData(oldp+961,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[4]),67);
            tracep->chgWData(oldp+964,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[5]),67);
            tracep->chgCData(oldp+967,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[0]),3);
            tracep->chgCData(oldp+968,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[1]),3);
            tracep->chgCData(oldp+969,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[2]),3);
            tracep->chgCData(oldp+970,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[3]),3);
            tracep->chgCData(oldp+971,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[4]),3);
            tracep->chgCData(oldp+972,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[5]),3);
            tracep->chgQData(oldp+973,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+975,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+977,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+979,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+981,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+983,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[5]),64);
            tracep->chgQData(oldp+985,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+987,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+988,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__i),32);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[2U])) {
            tracep->chgQData(oldp+989,(vlSelf->top__DOT__de__DOT__array[0]),64);
            tracep->chgQData(oldp+991,(vlSelf->top__DOT__de__DOT__array[1]),64);
            tracep->chgQData(oldp+993,(vlSelf->top__DOT__de__DOT__array[2]),64);
            tracep->chgQData(oldp+995,(vlSelf->top__DOT__de__DOT__array[3]),64);
            tracep->chgQData(oldp+997,(vlSelf->top__DOT__de__DOT__array[4]),64);
            tracep->chgQData(oldp+999,(vlSelf->top__DOT__de__DOT__array[5]),64);
            tracep->chgQData(oldp+1001,(vlSelf->top__DOT__de__DOT__array[6]),64);
            tracep->chgQData(oldp+1003,(vlSelf->top__DOT__de__DOT__array[7]),64);
            tracep->chgQData(oldp+1005,(vlSelf->top__DOT__de__DOT__array[8]),64);
            tracep->chgQData(oldp+1007,(vlSelf->top__DOT__de__DOT__array[9]),64);
            tracep->chgQData(oldp+1009,(vlSelf->top__DOT__de__DOT__array[10]),64);
            tracep->chgQData(oldp+1011,(vlSelf->top__DOT__de__DOT__array[11]),64);
            tracep->chgQData(oldp+1013,(vlSelf->top__DOT__de__DOT__array[12]),64);
            tracep->chgQData(oldp+1015,(vlSelf->top__DOT__de__DOT__array[13]),64);
            tracep->chgQData(oldp+1017,(vlSelf->top__DOT__de__DOT__array[14]),64);
            tracep->chgQData(oldp+1019,(vlSelf->top__DOT__de__DOT__array[15]),64);
            tracep->chgQData(oldp+1021,(vlSelf->top__DOT__de__DOT__array[16]),64);
            tracep->chgQData(oldp+1023,(vlSelf->top__DOT__de__DOT__array[17]),64);
            tracep->chgQData(oldp+1025,(vlSelf->top__DOT__de__DOT__array[18]),64);
            tracep->chgQData(oldp+1027,(vlSelf->top__DOT__de__DOT__array[19]),64);
            tracep->chgQData(oldp+1029,(vlSelf->top__DOT__de__DOT__array[20]),64);
            tracep->chgQData(oldp+1031,(vlSelf->top__DOT__de__DOT__array[21]),64);
            tracep->chgQData(oldp+1033,(vlSelf->top__DOT__de__DOT__array[22]),64);
            tracep->chgQData(oldp+1035,(vlSelf->top__DOT__de__DOT__array[23]),64);
            tracep->chgQData(oldp+1037,(vlSelf->top__DOT__de__DOT__array[24]),64);
            tracep->chgQData(oldp+1039,(vlSelf->top__DOT__de__DOT__array[25]),64);
            tracep->chgQData(oldp+1041,(vlSelf->top__DOT__de__DOT__array[26]),64);
            tracep->chgQData(oldp+1043,(vlSelf->top__DOT__de__DOT__array[27]),64);
            tracep->chgQData(oldp+1045,(vlSelf->top__DOT__de__DOT__array[28]),64);
            tracep->chgQData(oldp+1047,(vlSelf->top__DOT__de__DOT__array[29]),64);
            tracep->chgQData(oldp+1049,(vlSelf->top__DOT__de__DOT__array[30]),64);
            tracep->chgQData(oldp+1051,(vlSelf->top__DOT__de__DOT__array[31]),64);
            tracep->chgQData(oldp+1053,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[0]),64);
            tracep->chgQData(oldp+1055,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[1]),64);
            tracep->chgQData(oldp+1057,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[2]),64);
            tracep->chgQData(oldp+1059,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[3]),64);
            tracep->chgQData(oldp+1061,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[4]),64);
            tracep->chgQData(oldp+1063,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[5]),64);
            tracep->chgQData(oldp+1065,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[6]),64);
            tracep->chgQData(oldp+1067,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[7]),64);
            tracep->chgQData(oldp+1069,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[8]),64);
            tracep->chgQData(oldp+1071,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[9]),64);
            tracep->chgQData(oldp+1073,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[10]),64);
            tracep->chgQData(oldp+1075,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[11]),64);
            tracep->chgQData(oldp+1077,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[12]),64);
            tracep->chgQData(oldp+1079,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[13]),64);
            tracep->chgQData(oldp+1081,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[14]),64);
            tracep->chgQData(oldp+1083,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[15]),64);
            tracep->chgQData(oldp+1085,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[16]),64);
            tracep->chgQData(oldp+1087,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[17]),64);
            tracep->chgQData(oldp+1089,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[18]),64);
            tracep->chgQData(oldp+1091,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[19]),64);
            tracep->chgQData(oldp+1093,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[20]),64);
            tracep->chgQData(oldp+1095,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[21]),64);
            tracep->chgQData(oldp+1097,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[22]),64);
            tracep->chgQData(oldp+1099,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[23]),64);
            tracep->chgQData(oldp+1101,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[24]),64);
            tracep->chgQData(oldp+1103,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[25]),64);
            tracep->chgQData(oldp+1105,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[26]),64);
            tracep->chgQData(oldp+1107,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[27]),64);
            tracep->chgQData(oldp+1109,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[28]),64);
            tracep->chgQData(oldp+1111,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[29]),64);
            tracep->chgQData(oldp+1113,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[30]),64);
            tracep->chgQData(oldp+1115,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[31]),64);
            tracep->chgQData(oldp+1117,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[0]),64);
            tracep->chgQData(oldp+1119,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[1]),64);
            tracep->chgQData(oldp+1121,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[2]),64);
            tracep->chgQData(oldp+1123,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[3]),64);
            tracep->chgQData(oldp+1125,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[4]),64);
            tracep->chgQData(oldp+1127,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[5]),64);
            tracep->chgQData(oldp+1129,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[6]),64);
            tracep->chgQData(oldp+1131,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[7]),64);
            tracep->chgQData(oldp+1133,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[8]),64);
            tracep->chgQData(oldp+1135,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[9]),64);
            tracep->chgQData(oldp+1137,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[10]),64);
            tracep->chgQData(oldp+1139,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[11]),64);
            tracep->chgQData(oldp+1141,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[12]),64);
            tracep->chgQData(oldp+1143,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[13]),64);
            tracep->chgQData(oldp+1145,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[14]),64);
            tracep->chgQData(oldp+1147,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[15]),64);
            tracep->chgQData(oldp+1149,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[16]),64);
            tracep->chgQData(oldp+1151,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[17]),64);
            tracep->chgQData(oldp+1153,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[18]),64);
            tracep->chgQData(oldp+1155,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[19]),64);
            tracep->chgQData(oldp+1157,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[20]),64);
            tracep->chgQData(oldp+1159,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[21]),64);
            tracep->chgQData(oldp+1161,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[22]),64);
            tracep->chgQData(oldp+1163,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[23]),64);
            tracep->chgQData(oldp+1165,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[24]),64);
            tracep->chgQData(oldp+1167,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[25]),64);
            tracep->chgQData(oldp+1169,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[26]),64);
            tracep->chgQData(oldp+1171,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[27]),64);
            tracep->chgQData(oldp+1173,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[28]),64);
            tracep->chgQData(oldp+1175,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[29]),64);
            tracep->chgQData(oldp+1177,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[30]),64);
            tracep->chgQData(oldp+1179,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[31]),64);
        }
        tracep->chgBit(oldp+1181,(vlSelf->clk));
        tracep->chgBit(oldp+1182,(vlSelf->rst));
        tracep->chgIData(oldp+1183,(vlSelf->inst),32);
        tracep->chgIData(oldp+1184,(vlSelf->cpupc),32);
        tracep->chgBit(oldp+1185,((0x100073U == vlSelf->inst)));
        tracep->chgIData(oldp+1186,((0x100073U == vlSelf->inst)),32);
        tracep->chgQData(oldp+1187,((QData)((IData)(vlSelf->cpupc))),64);
        tracep->chgCData(oldp+1189,((3U & vlSelf->inst)),2);
        tracep->chgCData(oldp+1190,((0x1fU & (vlSelf->inst 
                                              >> 2U))),5);
        tracep->chgCData(oldp+1191,((7U & (vlSelf->inst 
                                           >> 0xcU))),3);
        tracep->chgCData(oldp+1192,((0x1fU & (vlSelf->inst 
                                              >> 0xfU))),5);
        tracep->chgCData(oldp+1193,((0x1fU & (vlSelf->inst 
                                              >> 0x14U))),5);
        tracep->chgCData(oldp+1194,((0x1fU & (vlSelf->inst 
                                              >> 7U))),5);
        tracep->chgIData(oldp+1195,((0x17U | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgIData(oldp+1196,((0xfffff000U & vlSelf->inst)),32);
        tracep->chgIData(oldp+1197,((0x37U | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgIData(oldp+1198,((0x6fU | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgQData(oldp+1199,((4ULL + (QData)((IData)(vlSelf->cpupc)))),64);
        tracep->chgIData(oldp+1201,(((IData)(4U) + vlSelf->cpupc)),32);
    }
}

void Vtop___024root__traceCleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    Vtop___024root* const __restrict vlSelf = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        vlSymsp->__Vm_activity = false;
        vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    }
}
