// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__traceChgSub0(Vtop___024root* vlSelf, VerilatedVcd* tracep);

void Vtop___024root__traceChgTop0(void* voidSelf, VerilatedVcd* tracep) {
    Vtop___024root* const __restrict vlSelf = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    {
        Vtop___024root__traceChgSub0((&vlSymsp->TOP), tracep);
    }
}

void Vtop___024root__traceChgSub0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode + 1);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[0U])) {
            tracep->chgIData(oldp+0,(vlSelf->top__DOT__de__DOT__r0__DOT__i),32);
            tracep->chgQData(oldp+1,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__pair_list[0]),37);
            tracep->chgIData(oldp+3,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__key_list[0]),32);
            tracep->chgCData(oldp+4,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__data_list[0]),5);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[1U])) {
            tracep->chgIData(oldp+5,(vlSelf->top__DOT__dnpc),32);
            tracep->chgQData(oldp+6,(vlSelf->top__DOT__de__DOT__mraddr),64);
            tracep->chgQData(oldp+8,(vlSelf->top__DOT__de__DOT__mrdata),64);
            tracep->chgQData(oldp+10,(vlSymsp->TOP__top__DOT__de__DOT__m10.out),64);
            tracep->chgQData(oldp+12,(vlSymsp->TOP__top__DOT__de__DOT__m9.out),64);
            tracep->chgCData(oldp+14,(vlSelf->top__DOT__de__DOT__mwmask),8);
            tracep->chgIData(oldp+15,((IData)(vlSelf->top__DOT__de__DOT__rdata)),32);
            tracep->chgCData(oldp+16,(vlSelf->top__DOT__de__DOT__call_return),2);
            tracep->chgIData(oldp+17,(vlSelf->top__DOT__de__DOT__call_return),32);
            tracep->chgCData(oldp+18,(vlSelf->top__DOT__de__DOT__Type),3);
            tracep->chgIData(oldp+19,(vlSelf->top__DOT__de__DOT__Type),32);
            tracep->chgCData(oldp+20,(vlSelf->top__DOT__de__DOT__raddr),5);
            tracep->chgQData(oldp+21,(vlSelf->top__DOT__de__DOT__src1),64);
            tracep->chgQData(oldp+23,(vlSelf->top__DOT__de__DOT__src2),64);
            tracep->chgQData(oldp+25,(vlSelf->top__DOT__de__DOT__rdata),64);
            tracep->chgQData(oldp+27,(vlSymsp->TOP__top__DOT__de__DOT__m1.out),64);
            tracep->chgQData(oldp+29,(vlSymsp->TOP__top__DOT__de__DOT__m7.out),64);
            tracep->chgCData(oldp+31,(vlSelf->top__DOT__de__DOT__waddr),5);
            tracep->chgQData(oldp+32,(vlSelf->top__DOT__de__DOT__wdata),64);
            tracep->chgQData(oldp+34,(vlSelf->top__DOT__de__DOT__addresult),64);
            tracep->chgQData(oldp+36,(vlSymsp->TOP__top__DOT__de__DOT__m4.out),64);
            tracep->chgQData(oldp+38,(vlSymsp->TOP__top__DOT__de__DOT__m5.out),64);
            tracep->chgQData(oldp+40,(vlSelf->top__DOT__de__DOT__compare),64);
            tracep->chgQData(oldp+42,(vlSelf->top__DOT__de__DOT__logr),64);
            tracep->chgQData(oldp+44,(vlSelf->top__DOT__de__DOT__arir),64);
            tracep->chgQData(oldp+46,(vlSelf->top__DOT__de__DOT__logl),64);
            tracep->chgQData(oldp+48,(vlSelf->top__DOT__de__DOT__aril),64);
            tracep->chgQData(oldp+50,(vlSelf->top__DOT__de__DOT__yu),64);
            tracep->chgQData(oldp+52,(vlSelf->top__DOT__de__DOT__huo),64);
            tracep->chgQData(oldp+54,(vlSelf->top__DOT__de__DOT__yihuo),64);
            tracep->chgQData(oldp+56,(vlSelf->top__DOT__de__DOT__cheng),64);
            tracep->chgQData(oldp+58,(vlSelf->top__DOT__de__DOT__chu),64);
            tracep->chgQData(oldp+60,(vlSelf->top__DOT__de__DOT__scheng),64);
            tracep->chgQData(oldp+62,(vlSelf->top__DOT__de__DOT__schu),64);
            tracep->chgQData(oldp+64,(vlSelf->top__DOT__de__DOT__syu),64);
            tracep->chgIData(oldp+66,(vlSelf->top__DOT__de__DOT__addi),32);
            tracep->chgIData(oldp+67,(vlSelf->top__DOT__de__DOT__andi),32);
            tracep->chgIData(oldp+68,(vlSelf->top__DOT__de__DOT__xori),32);
            tracep->chgIData(oldp+69,(vlSelf->top__DOT__de__DOT__sllw),32);
            tracep->chgIData(oldp+70,(vlSelf->top__DOT__de__DOT__srlw),32);
            tracep->chgIData(oldp+71,(vlSelf->top__DOT__de__DOT__sraw),32);
            tracep->chgIData(oldp+72,(vlSelf->top__DOT__de__DOT__srawd),32);
            tracep->chgIData(oldp+73,(vlSelf->top__DOT__de__DOT__addiw),32);
            tracep->chgIData(oldp+74,(vlSelf->top__DOT__de__DOT__slliw),32);
            tracep->chgIData(oldp+75,(vlSelf->top__DOT__de__DOT__srliw),32);
            tracep->chgIData(oldp+76,(vlSelf->top__DOT__de__DOT__sraiw),32);
            tracep->chgQData(oldp+77,(vlSelf->top__DOT__de__DOT__addauipc),64);
            tracep->chgQData(oldp+79,(vlSelf->top__DOT__de__DOT__luimid),64);
            tracep->chgIData(oldp+81,(vlSelf->top__DOT__de__DOT__jalr),32);
            tracep->chgIData(oldp+82,(vlSelf->top__DOT__de__DOT__sd),32);
            tracep->chgIData(oldp+83,(vlSelf->top__DOT__de__DOT__sh),32);
            tracep->chgIData(oldp+84,(vlSelf->top__DOT__de__DOT__sw),32);
            tracep->chgIData(oldp+85,(vlSelf->top__DOT__de__DOT__sb),32);
            tracep->chgIData(oldp+86,(vlSelf->top__DOT__de__DOT__lw),32);
            tracep->chgIData(oldp+87,(vlSelf->top__DOT__de__DOT__lh),32);
            tracep->chgIData(oldp+88,(vlSelf->top__DOT__de__DOT__lbu),32);
            tracep->chgIData(oldp+89,(vlSelf->top__DOT__de__DOT__lhu),32);
            tracep->chgIData(oldp+90,(vlSelf->top__DOT__de__DOT__ld),32);
            tracep->chgIData(oldp+91,(vlSelf->top__DOT__de__DOT__addw),32);
            tracep->chgIData(oldp+92,(vlSelf->top__DOT__de__DOT__subw),32);
            tracep->chgIData(oldp+93,(vlSelf->top__DOT__de__DOT__mulw),32);
            tracep->chgIData(oldp+94,(vlSelf->top__DOT__de__DOT__divw),32);
            tracep->chgIData(oldp+95,(vlSelf->top__DOT__de__DOT__remw),32);
            tracep->chgIData(oldp+96,(vlSelf->top__DOT__de__DOT__Add),32);
            tracep->chgIData(oldp+97,(vlSelf->top__DOT__de__DOT__Mul),32);
            tracep->chgIData(oldp+98,(vlSelf->top__DOT__de__DOT__And),32);
            tracep->chgIData(oldp+99,(vlSelf->top__DOT__de__DOT__Or),32);
            tracep->chgIData(oldp+100,(vlSelf->top__DOT__de__DOT__sltu),32);
            tracep->chgIData(oldp+101,(vlSelf->top__DOT__de__DOT__slt),32);
            tracep->chgIData(oldp+102,(vlSelf->top__DOT__de__DOT__sub),32);
            tracep->chgIData(oldp+103,(vlSelf->top__DOT__de__DOT__sltiu),32);
            tracep->chgIData(oldp+104,(vlSelf->top__DOT__de__DOT__srai),32);
            tracep->chgIData(oldp+105,(vlSelf->top__DOT__de__DOT__slli),32);
            tracep->chgIData(oldp+106,(vlSelf->top__DOT__de__DOT__srli),32);
            tracep->chgIData(oldp+107,(vlSelf->top__DOT__de__DOT__beq),32);
            tracep->chgIData(oldp+108,(vlSelf->top__DOT__de__DOT__bne),32);
            tracep->chgIData(oldp+109,(vlSelf->top__DOT__de__DOT__bge),32);
            tracep->chgIData(oldp+110,(vlSelf->top__DOT__de__DOT__bgeu),32);
            tracep->chgIData(oldp+111,(vlSelf->top__DOT__de__DOT__bltu),32);
            tracep->chgIData(oldp+112,(vlSelf->top__DOT__de__DOT__blt),32);
            tracep->chgWData(oldp+113,(vlSelf->top__DOT__de__DOT____Vcellinp__m0____pinNumber4),1575);
            tracep->chgCData(oldp+163,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__lut_out),3);
            tracep->chgBit(oldp+164,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+165,(vlSelf->top__DOT__de__DOT__m0__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+166,(vlSelf->top__DOT__de__DOT____Vcellinp__m2____pinNumber4),1295);
            tracep->chgCData(oldp+207,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__lut_out),5);
            tracep->chgBit(oldp+208,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+209,(vlSelf->top__DOT__de__DOT__m2__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+210,(vlSelf->top__DOT__de__DOT____Vcellinp__m3____pinNumber4),3360);
            tracep->chgQData(oldp+315,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+317,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+318,(vlSelf->top__DOT__de__DOT__m3__DOT__i0__DOT__i),32);
            tracep->chgCData(oldp+319,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__lut_out),5);
            tracep->chgBit(oldp+320,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+321,(vlSelf->top__DOT__de__DOT__m8__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+322,(vlSelf->top__DOT__de__DOT____Vcellinp__m6____pinNumber4),512);
            tracep->chgQData(oldp+338,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[0]),64);
            tracep->chgQData(oldp+340,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[1]),64);
            tracep->chgQData(oldp+342,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[2]),64);
            tracep->chgQData(oldp+344,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[3]),64);
            tracep->chgQData(oldp+346,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[4]),64);
            tracep->chgQData(oldp+348,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[5]),64);
            tracep->chgQData(oldp+350,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[6]),64);
            tracep->chgQData(oldp+352,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__pair_list[7]),64);
            tracep->chgIData(oldp+354,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+355,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+356,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+357,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[3]),32);
            tracep->chgIData(oldp+358,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[4]),32);
            tracep->chgIData(oldp+359,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[5]),32);
            tracep->chgIData(oldp+360,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[6]),32);
            tracep->chgIData(oldp+361,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__key_list[7]),32);
            tracep->chgIData(oldp+362,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[0]),32);
            tracep->chgIData(oldp+363,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[1]),32);
            tracep->chgIData(oldp+364,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[2]),32);
            tracep->chgIData(oldp+365,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[3]),32);
            tracep->chgIData(oldp+366,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[4]),32);
            tracep->chgIData(oldp+367,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[5]),32);
            tracep->chgIData(oldp+368,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[6]),32);
            tracep->chgIData(oldp+369,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__data_list[7]),32);
            tracep->chgIData(oldp+370,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__lut_out),32);
            tracep->chgBit(oldp+371,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+372,(vlSelf->top__DOT__de__DOT__m6__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+373,(vlSelf->top__DOT__de__DOT____Vcellinp__m12____pinNumber4),160);
            tracep->chgQData(oldp+378,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[0]),40);
            tracep->chgQData(oldp+380,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[1]),40);
            tracep->chgQData(oldp+382,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[2]),40);
            tracep->chgQData(oldp+384,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__pair_list[3]),40);
            tracep->chgIData(oldp+386,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+387,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+388,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+389,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__key_list[3]),32);
            tracep->chgCData(oldp+390,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[0]),8);
            tracep->chgCData(oldp+391,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[1]),8);
            tracep->chgCData(oldp+392,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[2]),8);
            tracep->chgCData(oldp+393,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__data_list[3]),8);
            tracep->chgCData(oldp+394,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__lut_out),8);
            tracep->chgBit(oldp+395,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+396,(vlSelf->top__DOT__de__DOT__m12__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+397,(vlSelf->top__DOT__de__DOT____Vcellinp__m14____pinNumber4),480);
            tracep->chgWData(oldp+412,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+415,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+418,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+421,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[3]),96);
            tracep->chgWData(oldp+424,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__pair_list[4]),96);
            tracep->chgIData(oldp+427,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+428,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+429,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+430,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[3]),32);
            tracep->chgIData(oldp+431,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__key_list[4]),32);
            tracep->chgQData(oldp+432,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+434,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+436,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+438,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+440,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+442,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+444,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__hit));
            tracep->chgIData(oldp+445,(vlSelf->top__DOT__de__DOT__m14__DOT__i0__DOT__i),32);
            tracep->chgWData(oldp+446,(vlSelf->top__DOT__de__DOT____Vcellinp__m9____pinNumber4),384);
            tracep->chgWData(oldp+458,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+461,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+464,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+467,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__pair_list[3]),96);
            tracep->chgIData(oldp+470,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+471,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+472,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+473,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__key_list[3]),32);
            tracep->chgQData(oldp+474,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+476,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+478,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+480,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+482,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+484,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+485,(vlSymsp->TOP__top__DOT__de__DOT__m9.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+486,(vlSelf->top__DOT__de__DOT____Vcellinp__m10____pinNumber4),384);
            tracep->chgWData(oldp+498,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[0]),96);
            tracep->chgWData(oldp+501,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[1]),96);
            tracep->chgWData(oldp+504,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[2]),96);
            tracep->chgWData(oldp+507,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__pair_list[3]),96);
            tracep->chgIData(oldp+510,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[0]),32);
            tracep->chgIData(oldp+511,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[1]),32);
            tracep->chgIData(oldp+512,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[2]),32);
            tracep->chgIData(oldp+513,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__key_list[3]),32);
            tracep->chgQData(oldp+514,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+516,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+518,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+520,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+522,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+524,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+525,(vlSymsp->TOP__top__DOT__de__DOT__m10.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+526,(vlSelf->top__DOT__de__DOT____Vcellinp__m4____pinNumber4),3936);
            tracep->chgQData(oldp+649,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+651,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+652,(vlSymsp->TOP__top__DOT__de__DOT__m4.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+653,(vlSelf->top__DOT__de__DOT____Vcellinp__m5____pinNumber4),3936);
            tracep->chgQData(oldp+776,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+778,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+779,(vlSymsp->TOP__top__DOT__de__DOT__m5.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+780,(vlSelf->top__DOT__de__DOT____Vcellinp__m1____pinNumber4),402);
            tracep->chgWData(oldp+793,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[0]),67);
            tracep->chgWData(oldp+796,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[1]),67);
            tracep->chgWData(oldp+799,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[2]),67);
            tracep->chgWData(oldp+802,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[3]),67);
            tracep->chgWData(oldp+805,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[4]),67);
            tracep->chgWData(oldp+808,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__pair_list[5]),67);
            tracep->chgCData(oldp+811,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[0]),3);
            tracep->chgCData(oldp+812,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[1]),3);
            tracep->chgCData(oldp+813,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[2]),3);
            tracep->chgCData(oldp+814,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[3]),3);
            tracep->chgCData(oldp+815,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[4]),3);
            tracep->chgCData(oldp+816,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__key_list[5]),3);
            tracep->chgQData(oldp+817,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+819,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+821,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+823,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+825,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+827,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__data_list[5]),64);
            tracep->chgQData(oldp+829,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+831,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+832,(vlSymsp->TOP__top__DOT__de__DOT__m1.__PVT__i0__DOT__i),32);
            tracep->chgWData(oldp+833,(vlSelf->top__DOT__de__DOT____Vcellinp__m7____pinNumber4),402);
            tracep->chgWData(oldp+846,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[0]),67);
            tracep->chgWData(oldp+849,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[1]),67);
            tracep->chgWData(oldp+852,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[2]),67);
            tracep->chgWData(oldp+855,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[3]),67);
            tracep->chgWData(oldp+858,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[4]),67);
            tracep->chgWData(oldp+861,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__pair_list[5]),67);
            tracep->chgCData(oldp+864,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[0]),3);
            tracep->chgCData(oldp+865,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[1]),3);
            tracep->chgCData(oldp+866,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[2]),3);
            tracep->chgCData(oldp+867,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[3]),3);
            tracep->chgCData(oldp+868,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[4]),3);
            tracep->chgCData(oldp+869,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__key_list[5]),3);
            tracep->chgQData(oldp+870,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[0]),64);
            tracep->chgQData(oldp+872,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[1]),64);
            tracep->chgQData(oldp+874,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[2]),64);
            tracep->chgQData(oldp+876,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[3]),64);
            tracep->chgQData(oldp+878,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[4]),64);
            tracep->chgQData(oldp+880,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__data_list[5]),64);
            tracep->chgQData(oldp+882,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__lut_out),64);
            tracep->chgBit(oldp+884,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__hit));
            tracep->chgIData(oldp+885,(vlSymsp->TOP__top__DOT__de__DOT__m7.__PVT__i0__DOT__i),32);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[2U])) {
            tracep->chgQData(oldp+886,(vlSelf->top__DOT__de__DOT__array[0]),64);
            tracep->chgQData(oldp+888,(vlSelf->top__DOT__de__DOT__array[1]),64);
            tracep->chgQData(oldp+890,(vlSelf->top__DOT__de__DOT__array[2]),64);
            tracep->chgQData(oldp+892,(vlSelf->top__DOT__de__DOT__array[3]),64);
            tracep->chgQData(oldp+894,(vlSelf->top__DOT__de__DOT__array[4]),64);
            tracep->chgQData(oldp+896,(vlSelf->top__DOT__de__DOT__array[5]),64);
            tracep->chgQData(oldp+898,(vlSelf->top__DOT__de__DOT__array[6]),64);
            tracep->chgQData(oldp+900,(vlSelf->top__DOT__de__DOT__array[7]),64);
            tracep->chgQData(oldp+902,(vlSelf->top__DOT__de__DOT__array[8]),64);
            tracep->chgQData(oldp+904,(vlSelf->top__DOT__de__DOT__array[9]),64);
            tracep->chgQData(oldp+906,(vlSelf->top__DOT__de__DOT__array[10]),64);
            tracep->chgQData(oldp+908,(vlSelf->top__DOT__de__DOT__array[11]),64);
            tracep->chgQData(oldp+910,(vlSelf->top__DOT__de__DOT__array[12]),64);
            tracep->chgQData(oldp+912,(vlSelf->top__DOT__de__DOT__array[13]),64);
            tracep->chgQData(oldp+914,(vlSelf->top__DOT__de__DOT__array[14]),64);
            tracep->chgQData(oldp+916,(vlSelf->top__DOT__de__DOT__array[15]),64);
            tracep->chgQData(oldp+918,(vlSelf->top__DOT__de__DOT__array[16]),64);
            tracep->chgQData(oldp+920,(vlSelf->top__DOT__de__DOT__array[17]),64);
            tracep->chgQData(oldp+922,(vlSelf->top__DOT__de__DOT__array[18]),64);
            tracep->chgQData(oldp+924,(vlSelf->top__DOT__de__DOT__array[19]),64);
            tracep->chgQData(oldp+926,(vlSelf->top__DOT__de__DOT__array[20]),64);
            tracep->chgQData(oldp+928,(vlSelf->top__DOT__de__DOT__array[21]),64);
            tracep->chgQData(oldp+930,(vlSelf->top__DOT__de__DOT__array[22]),64);
            tracep->chgQData(oldp+932,(vlSelf->top__DOT__de__DOT__array[23]),64);
            tracep->chgQData(oldp+934,(vlSelf->top__DOT__de__DOT__array[24]),64);
            tracep->chgQData(oldp+936,(vlSelf->top__DOT__de__DOT__array[25]),64);
            tracep->chgQData(oldp+938,(vlSelf->top__DOT__de__DOT__array[26]),64);
            tracep->chgQData(oldp+940,(vlSelf->top__DOT__de__DOT__array[27]),64);
            tracep->chgQData(oldp+942,(vlSelf->top__DOT__de__DOT__array[28]),64);
            tracep->chgQData(oldp+944,(vlSelf->top__DOT__de__DOT__array[29]),64);
            tracep->chgQData(oldp+946,(vlSelf->top__DOT__de__DOT__array[30]),64);
            tracep->chgQData(oldp+948,(vlSelf->top__DOT__de__DOT__array[31]),64);
            tracep->chgQData(oldp+950,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[0]),64);
            tracep->chgQData(oldp+952,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[1]),64);
            tracep->chgQData(oldp+954,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[2]),64);
            tracep->chgQData(oldp+956,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[3]),64);
            tracep->chgQData(oldp+958,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[4]),64);
            tracep->chgQData(oldp+960,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[5]),64);
            tracep->chgQData(oldp+962,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[6]),64);
            tracep->chgQData(oldp+964,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[7]),64);
            tracep->chgQData(oldp+966,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[8]),64);
            tracep->chgQData(oldp+968,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[9]),64);
            tracep->chgQData(oldp+970,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[10]),64);
            tracep->chgQData(oldp+972,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[11]),64);
            tracep->chgQData(oldp+974,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[12]),64);
            tracep->chgQData(oldp+976,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[13]),64);
            tracep->chgQData(oldp+978,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[14]),64);
            tracep->chgQData(oldp+980,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[15]),64);
            tracep->chgQData(oldp+982,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[16]),64);
            tracep->chgQData(oldp+984,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[17]),64);
            tracep->chgQData(oldp+986,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[18]),64);
            tracep->chgQData(oldp+988,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[19]),64);
            tracep->chgQData(oldp+990,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[20]),64);
            tracep->chgQData(oldp+992,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[21]),64);
            tracep->chgQData(oldp+994,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[22]),64);
            tracep->chgQData(oldp+996,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[23]),64);
            tracep->chgQData(oldp+998,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[24]),64);
            tracep->chgQData(oldp+1000,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[25]),64);
            tracep->chgQData(oldp+1002,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[26]),64);
            tracep->chgQData(oldp+1004,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[27]),64);
            tracep->chgQData(oldp+1006,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[28]),64);
            tracep->chgQData(oldp+1008,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[29]),64);
            tracep->chgQData(oldp+1010,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[30]),64);
            tracep->chgQData(oldp+1012,(vlSelf->top__DOT__de__DOT____Vcellout__r0____pinNumber13[31]),64);
            tracep->chgQData(oldp+1014,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[0]),64);
            tracep->chgQData(oldp+1016,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[1]),64);
            tracep->chgQData(oldp+1018,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[2]),64);
            tracep->chgQData(oldp+1020,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[3]),64);
            tracep->chgQData(oldp+1022,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[4]),64);
            tracep->chgQData(oldp+1024,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[5]),64);
            tracep->chgQData(oldp+1026,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[6]),64);
            tracep->chgQData(oldp+1028,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[7]),64);
            tracep->chgQData(oldp+1030,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[8]),64);
            tracep->chgQData(oldp+1032,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[9]),64);
            tracep->chgQData(oldp+1034,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[10]),64);
            tracep->chgQData(oldp+1036,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[11]),64);
            tracep->chgQData(oldp+1038,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[12]),64);
            tracep->chgQData(oldp+1040,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[13]),64);
            tracep->chgQData(oldp+1042,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[14]),64);
            tracep->chgQData(oldp+1044,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[15]),64);
            tracep->chgQData(oldp+1046,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[16]),64);
            tracep->chgQData(oldp+1048,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[17]),64);
            tracep->chgQData(oldp+1050,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[18]),64);
            tracep->chgQData(oldp+1052,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[19]),64);
            tracep->chgQData(oldp+1054,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[20]),64);
            tracep->chgQData(oldp+1056,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[21]),64);
            tracep->chgQData(oldp+1058,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[22]),64);
            tracep->chgQData(oldp+1060,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[23]),64);
            tracep->chgQData(oldp+1062,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[24]),64);
            tracep->chgQData(oldp+1064,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[25]),64);
            tracep->chgQData(oldp+1066,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[26]),64);
            tracep->chgQData(oldp+1068,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[27]),64);
            tracep->chgQData(oldp+1070,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[28]),64);
            tracep->chgQData(oldp+1072,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[29]),64);
            tracep->chgQData(oldp+1074,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[30]),64);
            tracep->chgQData(oldp+1076,(vlSelf->top__DOT__de__DOT__r0__DOT__rf[31]),64);
        }
        tracep->chgBit(oldp+1078,(vlSelf->clk));
        tracep->chgBit(oldp+1079,(vlSelf->rst));
        tracep->chgIData(oldp+1080,(vlSelf->inst),32);
        tracep->chgIData(oldp+1081,(vlSelf->cpupc),32);
        tracep->chgBit(oldp+1082,((0x100073U == vlSelf->inst)));
        tracep->chgIData(oldp+1083,((0x100073U == vlSelf->inst)),32);
        tracep->chgQData(oldp+1084,((QData)((IData)(vlSelf->cpupc))),64);
        tracep->chgCData(oldp+1086,((3U & vlSelf->inst)),2);
        tracep->chgCData(oldp+1087,((0x1fU & (vlSelf->inst 
                                              >> 2U))),5);
        tracep->chgCData(oldp+1088,((7U & (vlSelf->inst 
                                           >> 0xcU))),3);
        tracep->chgCData(oldp+1089,((0x1fU & (vlSelf->inst 
                                              >> 0xfU))),5);
        tracep->chgCData(oldp+1090,((0x1fU & (vlSelf->inst 
                                              >> 0x14U))),5);
        tracep->chgCData(oldp+1091,((0x1fU & (vlSelf->inst 
                                              >> 7U))),5);
        tracep->chgIData(oldp+1092,((0x17U | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgIData(oldp+1093,((0xfffff000U & vlSelf->inst)),32);
        tracep->chgIData(oldp+1094,((0x37U | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgIData(oldp+1095,((0x6fU | (0xffffff80U 
                                              & vlSelf->inst))),32);
        tracep->chgQData(oldp+1096,((4ULL + (QData)((IData)(vlSelf->cpupc)))),64);
        tracep->chgIData(oldp+1098,(((IData)(4U) + vlSelf->cpupc)),32);
    }
}

void Vtop___024root__traceCleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    Vtop___024root* const __restrict vlSelf = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        vlSymsp->__Vm_activity = false;
        vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    }
}
